spring.datasource.url=jdbc:mysql://localhost:3307/db_prizeasy
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=VkHjkQQWuFpqnmmDofHS7ng78epw+bRVfiL2AaDufmA=
